### ISSUE TITLE
How to get or create this Image GUID

### ISSUE THREAD

**Issue by goxia** [MicrosoftDocs/commercialization-public#257]
How to get or create this Image GUID?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d566ecb-54a4-2ebf-cea6-68244db59173
* Version Independent ID: 70924974-7952-0a92-b3f2-a8b13039ce41
* Content: [Configure a Trusted Image Identifier for Windows Defender](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/configure-a-trusted-image-identifier-for-windows-defender#feedback)
* Content Source: [manufacture/desktop/configure-a-trusted-image-identifier-for-windows-defender.md](https://github.com/MicrosoftDocs/commercialization-public/blob/master/manufacture/desktop/configure-a-trusted-image-identifier-for-windows-defender.md)
* Product: **windows-hardware**
* GitHub Login: @themar
* Microsoft Alias: **themar**

**Comment by kpacquer** [comment]
Any unique value will do. If you want something meaningful, consider using the device's model name plus your own image identifier (Contoso-Laptop-image-2018-07-31).
GUIDs are often handy because you can generate them on the spot without worrying too much about whether that value has already been used. There's plenty of tools you can use to create them; I like GUIDGen.exe, built into Visual Studio and SDK tools: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\guidgen.exe. 
We recommend creating a new ID for each image that you're deploying. That way, if you find a security problem with that image, then only the affected devices will require full scans upon startup.

**Comment by goxia** [comment]
Thank you, then this trustedimageidentifier if the system is bound? Will it be recognized simply by writing to this value as a document?

**Comment by kpacquer** [comment]
The setting only works when setting up new PC from scratch using a [Windows Setup unattend answer file](https://docs.microsoft.com/windows-hardware/manufacture/desktop/update-windows-settings-and-scripts-create-your-own-answer-file-sxs).
